name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create release version name
        id: createReleaseVersionName
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')" >> "$GITHUB_OUTPUT"

      - name: Create PR Branch Name
        id: createPrBranchName
        env:
          RELEASE_VERSION: ${{ steps.createReleaseVersionName.outputs.RELEASE_VERSION }}
        run: |
          echo "PR_BRANCH_NAME=publish-v$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Release with Maven
        env:
          PR_BRANCH_NAME: ${{ steps.createPrBranchName.outputs.PR_BRANCH_NAME }}
          GIT_USER_NAME: acrolinx-opensource
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_KEY: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.CODE_SIGNING_PWD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
        run: |
          git config user.email opensource@acrolinx.com
          git config user.name $GIT_USER_NAME
          git checkout -b $PR_BRANCH_NAME
          mvn -s .m2/settings.xml  -P sign -B -Dusername=$GIT_USER_NAME -Dpassword=$GITHUB_TOKEN -DpreparationGoals="clean spotless:apply verify" -DcompletionGoals="spotless:apply" release:prepare release:perform -Dgpg.signer=bc -e
