name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Release with Maven
        run: git config --global user.email GIT_USER_EMAIL
        run: git config --global user.name GIT_USER_NAME
        run: mvn clean -B -Dusername=$GIT_USER_NAME -Dpassword=GITHUB_TOKEN release:prepare release:perform
        env:
          GIT_USER_NAME: acrolinx-opensource
          GIT_USER_EMAIL: opensource@acrolinx.com
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
